<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { IonContent,IonPage,IonRefresher,IonRefresherContent,IonSearchbar,toastController } from '@ionic/vue'
import PageHeader from '../components/PageHeader.vue';import { api,ApiError } from '../api';import { amount } from '../expenses'
type Month={month:string;total_profit:number;record_count:number;store_count:number;reporter_count:number;latest_report_date:string|null};type Profit={source_record_id:number;report_date:string;store_name:string;profit:number;reporter_name:string;synced_at:string}
const summary=ref<Record<string,number|string|null>>({});const months=ref<Month[]>([]);const records=ref<Profit[]>([]);const query=ref('');const filtered=computed(()=>records.value.filter(item=>!query.value||`${item.store_name} ${item.reporter_name} ${item.report_date}`.toLowerCase().includes(query.value.toLowerCase())));const max=computed(()=>Math.max(...months.value.map(item=>Math.abs(item.total_profit)),1))
const load=async(event?:{target:{complete:()=>void}})=>{try{const data=await Promise.all([api<Record<string,number|string|null>>('/dingtalk-profits/summary'),api<Month[]>('/dingtalk-profits/monthly-summary'),api<Profit[]>('/dingtalk-profits')]);summary.value=data[0];months.value=data[1];records.value=data[2]}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'利润数据加载失败',duration:2200,color:'danger'});await toast.present()}finally{event?.target.complete()}};onMounted(load)
</script>
<template><IonPage><PageHeader title="钉钉利润" :subtitle="`${records.length} 条同步记录`" back /><IonContent><IonRefresher slot="fixed" @ion-refresh="load"><IonRefresherContent /></IonRefresher><main class="page-pad profit-page"><section class="metric-strip"><article class="metric"><span>累计利润</span><strong>{{ amount(Number(summary.total_profit||0)) }}</strong></article><article class="metric"><span>店铺数</span><strong>{{ summary.unique_store_count||0 }} 家</strong></article><article class="metric"><span>报表人数</span><strong>{{ summary.unique_reporter_count||0 }} 人</strong></article></section><div class="section-title"><h2>月度利润趋势</h2><span>左右滑动</span></div><section class="chart panel"><div v-for="item in months" :key="item.month" class="bar-item"><div class="bar-wrap"><span :style="{height:`${Math.max(Math.abs(item.total_profit)/max*100,4)}%`}" :class="{negative:item.total_profit<0}"></span></div><b>{{ item.month.slice(5) }}月</b><small>{{ amount(item.total_profit) }}</small></div></section><div class="section-title"><h2>利润明细</h2><span>{{ filtered.length }} 条</span></div><IonSearchbar v-model="query" placeholder="搜索店铺、上报人或日期" mode="ios" /><section class="compact-list"><div v-for="item in filtered" :key="item.source_record_id" class="compact-row profit-row"><span class="profit-icon">¥</span><div><h3>{{ item.store_name }}</h3><p>{{ item.report_date }} · {{ item.reporter_name }}</p></div><strong :class="{negative:item.profit<0}">{{ amount(item.profit) }}</strong></div></section></main></IonContent></IonPage></template>
<style scoped>.profit-page ion-searchbar{--background:var(--app-card);--box-shadow:none;--border-radius:14px;padding:0;margin-bottom:10px}.chart{display:grid;grid-auto-flow:column;grid-auto-columns:72px;gap:10px;height:220px;padding:18px 14px;overflow-x:auto}.bar-item{display:grid;grid-template-rows:1fr auto auto;gap:5px;text-align:center}.bar-wrap{display:flex;align-items:end;justify-content:center;border-bottom:1px solid var(--app-line)}.bar-wrap span{width:28px;min-height:4px;border-radius:8px 8px 2px 2px;background:linear-gradient(#6366f1,#3b82f6)}.bar-wrap span.negative{background:linear-gradient(#fb7185,#ef4444)}.bar-item b{font-size:12px}.bar-item small{color:var(--app-muted);font-size:9px}.profit-row strong{color:#10b981;font-size:13px}.profit-row strong.negative{color:#ef4444}.profit-icon{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;color:#f59e0b;background:#fff4d6;font-weight:700}</style>
