<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { IonContent, IonPage, alertController, toastController } from '@ionic/vue'
import PageHeader from '../components/PageHeader.vue'
import { api, ApiError } from '../api'
import type { FieldDefinition } from '../shopRecords'
const fields=ref<FieldDefinition[]>([])
const fail=async(e:unknown)=>{const t=await toastController.create({message:e instanceof ApiError?e.detail:'操作失败',duration:2200,color:'danger'});await t.present()}
const load=async()=>{try{fields.value=(await api<FieldDefinition[]>('/custom-fields')).sort((a,b)=>a.sort_order-b.sort_order)}catch(e){fail(e)}}
const add=async()=>{const a=await alertController.create({header:'新增店铺字段',inputs:[{name:'label',placeholder:'字段名称'},{name:'field_name',placeholder:'英文标识，如 manager_phone'},{name:'field_type',type:'radio',label:'文本',value:'text',checked:true},{name:'field_type',type:'radio',label:'数字',value:'number'},{name:'field_type',type:'radio',label:'日期',value:'date'}],buttons:['取消',{text:'新增',role:'confirm'}]});await a.present();const r=await a.onDidDismiss();if(r.role!=='confirm')return;try{await api('/custom-fields',{method:'POST',body:JSON.stringify({...r.data.values,required:false})});await load()}catch(e){fail(e)}}
const update=async(f:FieldDefinition,data:Record<string,unknown>)=>{try{await api(`/custom-fields/${f.id}`,{method:'PATCH',body:JSON.stringify(data)});await load()}catch(e){fail(e)}}
const move=async(i:number,d:number)=>{const j=i+d;if(j<0||j>=fields.value.length)return;const list=[...fields.value];[list[i],list[j]]=[list[j],list[i]];try{await api('/custom-fields/reorder',{method:'POST',body:JSON.stringify({field_ids:list.map(f=>f.id)})});fields.value=list}catch(e){fail(e)}}
const remove=async(f:FieldDefinition)=>{const a=await alertController.create({header:'删除字段',message:`确定删除“${f.label}”吗？`,buttons:['取消',{text:'删除',role:'destructive',handler:async()=>{try{await api(`/custom-fields/${f.id}`,{method:'DELETE'});await load()}catch(e){fail(e)}}}]});await a.present()}
onMounted(load)
</script>
<template><IonPage><PageHeader title="店铺字段管理" subtitle="与电脑端字段保持同步" back /><IonContent><main><div class="toolbar"><span>{{ fields.length }} 个字段</span><button @click="add">新增字段</button></div><section><article v-for="(f,i) in fields" :key="f.id"><div><strong>{{ f.label }}</strong><small>{{ f.field_name }} · {{ {text:'文本',number:'数字',date:'日期'}[f.field_type] }}{{ f.is_builtin?' · 系统字段':'' }}</small></div><label><input type="checkbox" :checked="f.is_visible" :disabled="f.is_builtin" @change="update(f,{is_visible:($event.target as HTMLInputElement).checked})">显示</label><label><input type="checkbox" :checked="f.required" @change="update(f,{required:($event.target as HTMLInputElement).checked})">必填</label><footer><button :disabled="i===0" @click="move(i,-1)">上移</button><button :disabled="i===fields.length-1" @click="move(i,1)">下移</button><button v-if="!f.is_builtin" class="danger" @click="remove(f)">删除</button></footer></article></section></main></IonContent></IonPage></template>
<style scoped>main{padding:14px}.toolbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;color:var(--app-muted)}button{padding:8px 11px;border:1px solid var(--app-line);border-radius:9px;color:#2563eb;background:var(--app-card)}section{overflow:hidden;border:1px solid var(--app-line);border-radius:14px;background:var(--app-card)}article{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:10px;align-items:center;padding:14px;border-bottom:1px solid var(--app-line)}article:last-child{border-bottom:0}small{display:block;margin-top:4px;color:var(--app-muted);font-size:11px}label{font-size:12px;white-space:nowrap}footer{grid-column:1/4;display:flex;justify-content:flex-end;gap:7px}.danger{color:#dc2626}button:disabled{opacity:.35}</style>
