<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { IonButton, IonContent, IonFooter, IonInput, IonItem, IonLabel, IonPage, IonSpinner, IonTextarea, IonToolbar, toastController } from '@ionic/vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { api, ApiError } from '../api'
import { session } from '../session'
import type { NamedOption, TaskRecord, TaskStatus } from '../taskRecords'
const route=useRoute();const router=useRouter();const editing=computed(()=>Boolean(route.params.id));const loading=ref(true);const saving=ref(false)
const shops=ref<NamedOption[]>([]);const owners=ref<NamedOption[]>([]);const canWrite=computed(()=>['editor','superadmin'].includes(session.user?.role||''))
const form=reactive({task_time:'',shop_name:'',owner_name:'',principal_amount:'0',order_count:'1',commission_amount:'0',gift_amount:'0',signed_status:'pending' as TaskStatus,settlement_status:'pending' as TaskStatus,note:''})
const localDateTime=(value?:string|null)=>{const date=value?new Date(value):new Date();const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
const load=async()=>{if(!canWrite.value){const toast=await toastController.create({message:'当前账号只有查看权限',duration:1800,color:'warning'});await toast.present();router.back();return}try{const data=await Promise.all([api<NamedOption[]>('/task-bookkeeping/shops'),api<NamedOption[]>('/task-bookkeeping/owners')]);shops.value=data[0];owners.value=data[1];if(editing.value){const record=await api<TaskRecord>(`/task-bookkeeping/records/${route.params.id}`);form.task_time=localDateTime(record.task_time);form.shop_name=record.shop_name;form.owner_name=record.owner_name;form.principal_amount=String(record.principal_amount);form.order_count=String(record.order_count);form.commission_amount=String(record.commission_amount);form.gift_amount=String(record.gift_amount);form.signed_status=record.signed_status;form.settlement_status=record.settlement_status;form.note=record.note||''}else form.task_time=localDateTime()}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'表单加载失败',duration:2200,color:'danger'});await toast.present()}finally{loading.value=false}}
const save=async()=>{if(!form.shop_name.trim()||!form.owner_name.trim()){const toast=await toastController.create({message:'请填写店铺名称和负责人',duration:1800,color:'warning'});await toast.present();return}saving.value=true;try{const payload={task_time:form.task_time||null,shop_name:form.shop_name,owner_name:form.owner_name,principal_amount:Number(form.principal_amount||0),order_count:Number(form.order_count||1),commission_amount:Number(form.commission_amount||0),gift_amount:Number(form.gift_amount||0),signed_status:form.signed_status,settlement_status:form.settlement_status,note:form.note||null};await api(editing.value?`/task-bookkeeping/records/${route.params.id}`:'/task-bookkeeping/records',{method:editing.value?'PUT':'POST',body:JSON.stringify(payload)});const toast=await toastController.create({message:editing.value?'任务已保存':'任务已新增',duration:1500,color:'success'});await toast.present();router.back()}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'保存失败',duration:2300,color:'danger'});await toast.present()}finally{saving.value=false}}
onMounted(load)
</script>
<template><IonPage><PageHeader :title="editing?'编辑任务记录':'新增任务记录'" subtitle="返回上一级" back /><IonContent><main class="page-pad task-form"><div v-if="loading" class="loading"><IonSpinner />正在加载</div><template v-else>
  <section class="panel form-panel"><IonItem><IonLabel position="stacked">任务时间 *</IonLabel><IonInput v-model="form.task_time" type="datetime-local" /></IonItem><IonItem><IonLabel position="stacked">店铺名称 *</IonLabel><IonInput v-model="form.shop_name" placeholder="选择或输入店铺名称" /></IonItem><div v-if="shops.length" class="suggestions"><button v-for="item in shops.slice(0,8)" :key="item.id" @click="form.shop_name=item.name">{{ item.name }}</button></div><IonItem><IonLabel position="stacked">负责人 *</IonLabel><IonInput v-model="form.owner_name" placeholder="选择或输入负责人" /></IonItem><div v-if="owners.length" class="suggestions"><button v-for="item in owners.slice(0,8)" :key="item.id" @click="form.owner_name=item.name">{{ item.name }}</button></div></section>
  <section class="panel form-panel money-grid"><IonItem><IonLabel position="stacked">刷单数量</IonLabel><IonInput v-model="form.order_count" type="number" inputmode="numeric" /></IonItem><IonItem><IonLabel position="stacked">单笔本金</IonLabel><IonInput v-model="form.principal_amount" type="number" inputmode="decimal" /></IonItem><IonItem><IonLabel position="stacked">佣金支出</IonLabel><IonInput v-model="form.commission_amount" type="number" inputmode="decimal" /></IonItem><IonItem><IonLabel position="stacked">礼品花费</IonLabel><IonInput v-model="form.gift_amount" type="number" inputmode="decimal" /></IonItem></section>
  <section class="panel status-panel"><label>签收状态</label><div><button :class="{active:form.signed_status==='pending'}" @click="form.signed_status='pending'">处理中</button><button :class="{active:form.signed_status==='completed'}" @click="form.signed_status='completed'">已完成</button></div><label>结算状态</label><div><button :class="{active:form.settlement_status==='pending'}" @click="form.settlement_status='pending'">处理中</button><button :class="{active:form.settlement_status==='completed'}" @click="form.settlement_status='completed'">已完成</button></div></section>
  <section class="panel form-panel"><IonItem lines="none"><IonLabel position="stacked">备注</IonLabel><IonTextarea v-model="form.note" :auto-grow="true" placeholder="填写任务说明或补充信息" /></IonItem></section>
</template></main></IonContent><IonFooter class="save-footer"><IonToolbar><div><IonButton fill="outline" :disabled="saving" @click="router.back()">取消</IonButton><IonButton :disabled="saving||loading" @click="save"><IonSpinner v-if="saving" />{{ saving?'保存中':editing?'保存修改':'新增任务' }}</IonButton></div></IonToolbar></IonFooter></IonPage></template>
<style scoped>.task-form{display:grid;gap:12px;padding-bottom:24px}.loading{display:flex;justify-content:center;gap:9px;padding:70px;color:var(--app-muted)}.form-panel ion-item{--background:var(--app-card);--padding-start:16px;--inner-padding-end:16px;--min-height:76px}.form-panel ion-input,.form-panel ion-textarea{font-size:16px}.suggestions{display:flex;gap:7px;overflow-x:auto;padding:0 14px 12px}.suggestions button{white-space:nowrap;border:1px solid var(--app-line);border-radius:999px;padding:6px 10px;color:#2563eb;background:#eff5ff}.money-grid{display:grid;grid-template-columns:1fr 1fr}.money-grid ion-item:nth-child(even){border-left:1px solid var(--app-line)}.status-panel{padding:15px}.status-panel label{display:block;margin:3px 0 8px;color:var(--app-muted);font-size:13px}.status-panel div{display:grid;grid-template-columns:1fr 1fr;margin-bottom:14px}.status-panel div:last-child{margin-bottom:0}.status-panel button{padding:11px;border:1px solid var(--app-line);color:var(--app-muted);background:var(--app-card)}.status-panel button:first-child{border-radius:11px 0 0 11px}.status-panel button:last-child{border-radius:0 11px 11px 0}.status-panel button.active{z-index:1;color:#fff;border-color:#6366f1;background:#6366f1}.save-footer ion-toolbar{--background:var(--app-card);--border-color:var(--app-line)}.save-footer div{display:grid;grid-template-columns:1fr 2fr;gap:10px;padding:10px 16px calc(10px + env(safe-area-inset-bottom))}.save-footer ion-button{height:48px;--border-radius:13px}</style>
