<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { IonContent, IonIcon, IonItem, IonItemOption, IonItemOptions, IonItemSliding, IonList, IonPage, IonRefresher, IonRefresherContent, IonSearchbar, alertController, toastController } from '@ionic/vue'
import { addOutline, checkmarkCircleOutline, createOutline, trashOutline } from 'ionicons/icons'
import { useRouter } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { api, ApiError } from '../api'
import { session } from '../session'
import { dateTime, loadTaskData, money, type TaskRecord, type TaskStatus, type TaskSummary } from '../taskRecords'

const router=useRouter(); const loading=ref(true); const query=ref(''); const signed=ref(''); const settlement=ref('')
const records=ref<TaskRecord[]>([]); const summary=ref<TaskSummary | null>(null); const batch=ref(false); const selected=ref<number[]>([])
const canWrite=computed(()=>['editor','superadmin'].includes(session.user?.role || ''))
const filtered=computed(()=>records.value.filter((record)=>{
  const keyword=query.value.trim().toLowerCase(); const text=`${record.order_no} ${record.shop_name} ${record.owner_name} ${record.note || ''}`.toLowerCase()
  return (!keyword || text.includes(keyword)) && (!signed.value || record.signed_status===signed.value) && (!settlement.value || record.settlement_status===settlement.value)
}))
const load=async(event?:{target:{complete:()=>void}})=>{try{const data=await loadTaskData();summary.value=data.summary;records.value=data.records}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'任务加载失败',duration:2200,color:'danger'});await toast.present()}finally{loading.value=false;event?.target.complete()}}
const toggle=(id:number)=>selected.value=selected.value.includes(id)?selected.value.filter((item)=>item!==id):[...selected.value,id]
const updateStatus=async(ids:number[],field:'signed_status'|'settlement_status',value:TaskStatus)=>{if(!ids.length)return;try{await api('/task-bookkeeping/records/batch-status',{method:'PATCH',body:JSON.stringify({record_ids:ids,field,value})});records.value=records.value.map((record)=>ids.includes(record.id)?{...record,[field]:value}:record);selected.value=[];await load()}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'状态更新失败',duration:2200,color:'danger'});await toast.present()}}
const remove=async(ids:number[])=>{if(!ids.length)return;const alert=await alertController.create({header:ids.length>1?'批量删除任务':'删除任务记录',message:`确定删除选中的 ${ids.length} 条任务吗？`,buttons:['取消',{text:'删除',role:'destructive',handler:async()=>{try{if(ids.length===1)await api<void>(`/task-bookkeeping/records/${ids[0]}`,{method:'DELETE'});else await api('/task-bookkeeping/records/batch-delete',{method:'POST',body:JSON.stringify({record_ids:ids})});records.value=records.value.filter((item)=>!ids.includes(item.id));selected.value=[]}catch(error){const toast=await toastController.create({message:error instanceof ApiError?error.detail:'删除失败',duration:2200,color:'danger'});await toast.present()}}}]});await alert.present()}
onMounted(()=>load())
</script>

<template><IonPage><PageHeader title="任务记录" :subtitle="`${records.length} 条记录`" back /><IonContent>
  <IonRefresher slot="fixed" @ion-refresh="load"><IonRefresherContent pulling-text="下拉刷新" /></IonRefresher>
  <main class="page-pad task-page">
    <section class="metric-strip"><article class="metric"><span>任务记录</span><strong>{{ summary?.total_records || 0 }} 条</strong></article><article class="metric"><span>本金投入</span><strong>{{ money(summary?.principal_total || 0) }}</strong></article><article class="metric"><span>佣金支出</span><strong>{{ money(summary?.commission_total || 0) }}</strong></article><article class="metric"><span>待签收 / 待结算</span><strong>{{ summary?.pending_signed_count || 0 }} / {{ summary?.pending_settlement_count || 0 }}</strong></article></section>
    <div class="search-line"><IonSearchbar v-model="query" placeholder="搜索订单号、店铺、负责人或备注" mode="ios" /><button v-if="canWrite" @click="router.push('/tabs/form/tasks')"><IonIcon :icon="addOutline" />新增</button></div>
    <div class="filters"><button :class="{active:!signed}" @click="signed=''">全部签收</button><button :class="{active:signed==='pending'}" @click="signed='pending'">待签收</button><button :class="{active:signed==='completed'}" @click="signed='completed'">已签收</button><button :class="{active:settlement==='pending'}" @click="settlement=settlement==='pending'?'':'pending'">待结算</button></div>
    <div class="result-line"><span>显示 {{ filtered.length }} 条</span><button v-if="canWrite" @click="batch=!batch;selected=[]">{{ batch?'退出批量':'批量管理' }}</button></div>
    <IonList v-if="filtered.length" class="task-list" lines="none"><IonItemSliding v-for="record in filtered" :key="record.id" :disabled="batch">
      <IonItem class="task-item" button :detail="false" @click="batch?toggle(record.id):router.push(`/tabs/detail/tasks/${record.id}`)"><article class="task-card" :class="{selected:selected.includes(record.id)}"><header><span v-if="batch" class="check">{{ selected.includes(record.id)?'✓':'' }}</span><div><small>{{ record.order_no }} · {{ dateTime(record.task_time) }}</small><h2>{{ record.shop_name }}</h2><p>{{ record.owner_name }} · {{ record.order_count }} 单</p></div><strong>{{ money(record.principal_amount) }}</strong></header><div class="amounts"><span>佣金 <b>{{ money(record.commission_amount) }}</b></span><span>礼品 <b>{{ money(record.gift_amount) }}</b></span></div><footer><button :class="record.signed_status" @click.stop="canWrite&&updateStatus([record.id],'signed_status',record.signed_status==='pending'?'completed':'pending')">{{ record.signed_status==='completed'?'已签收':'待签收' }}</button><button :class="record.settlement_status" @click.stop="canWrite&&updateStatus([record.id],'settlement_status',record.settlement_status==='pending'?'completed':'pending')">{{ record.settlement_status==='completed'?'已结算':'待结算' }}</button><span>{{ record.note || '无备注' }}</span></footer></article></IonItem>
      <IonItemOptions v-if="canWrite" side="end"><IonItemOption color="primary" @click="router.push(`/tabs/form/tasks/${record.id}`)"><IonIcon slot="icon-only" :icon="createOutline" /></IonItemOption><IonItemOption color="danger" @click="remove([record.id])"><IonIcon slot="icon-only" :icon="trashOutline" /></IonItemOption></IonItemOptions>
    </IonItemSliding></IonList><div v-else-if="!loading" class="empty-state">没有符合条件的任务记录</div>
  </main>
  <div v-if="batch&&selected.length" class="batch-bar"><span>已选 {{ selected.length }} 条</span><button @click="updateStatus(selected,'signed_status','completed')"><IonIcon :icon="checkmarkCircleOutline" />签收</button><button @click="updateStatus(selected,'settlement_status','completed')">结算</button><button class="danger" @click="remove(selected)"><IonIcon :icon="trashOutline" /></button></div>
</IonContent></IonPage></template>

<style scoped>.task-page{padding-inline:12px}.metric-strip{margin-bottom:14px}.search-line{display:grid;grid-template-columns:1fr auto;gap:8px}.search-line ion-searchbar{--background:var(--app-card);--box-shadow:none;--border-radius:14px;padding:0}.search-line>button{border:0;border-radius:13px;padding:0 14px;color:#fff;background:#2563eb;display:flex;align-items:center;gap:4px}.filters{display:flex;gap:7px;overflow-x:auto;padding:10px 1px}.filters button,.result-line button{white-space:nowrap;border:1px solid var(--app-line);border-radius:999px;padding:7px 12px;color:var(--app-muted);background:var(--app-card)}.filters .active{color:#2563eb;border-color:#93b4ff;background:#eff5ff}.result-line{display:flex;justify-content:space-between;align-items:center;margin:2px 4px 10px;color:var(--app-muted);font-size:12px}.result-line button{padding:6px 11px}.task-list{padding:0;background:transparent;display:grid;gap:10px}.task-item{--padding-start:0;--inner-padding-end:0;--background:transparent}.task-card{width:100%;padding:15px;border:1px solid var(--app-line);border-radius:18px;background:var(--app-card)}.task-card.selected{border-color:#3b82f6;background:color-mix(in srgb,#3b82f6 7%,var(--app-card))}.task-card header{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:start}.task-card small,.task-card p{color:var(--app-muted);font-size:11px}.task-card h2,.task-card p{margin:4px 0 0}.task-card h2{font-size:17px}.task-card header>strong{font-size:17px;color:#2563eb}.check{width:22px;height:22px;border:1px solid #8fb3ff;border-radius:7px;display:grid;place-items:center;color:#fff;background:#2563eb}.amounts{display:grid;grid-template-columns:1fr 1fr;margin-top:12px;padding:10px 0;border-block:1px solid var(--app-line);color:var(--app-muted);font-size:12px}.amounts span+span{padding-left:12px;border-left:1px solid var(--app-line)}.amounts b{display:block;margin-top:4px;color:var(--app-text);font-size:14px}.task-card footer{display:flex;align-items:center;gap:7px;margin-top:11px}.task-card footer button{border:0;border-radius:999px;padding:5px 9px;font-size:11px}.task-card footer .pending{color:#b45309;background:#fff4d6}.task-card footer .completed{color:#047857;background:#dcfce7}.task-card footer span{min-width:0;margin-left:auto;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--app-muted);font-size:11px}.batch-bar{position:fixed;z-index:20;left:12px;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));display:flex;align-items:center;gap:8px;padding:10px 12px;border:1px solid var(--app-line);border-radius:16px;background:var(--app-card);box-shadow:0 12px 35px rgba(15,23,42,.18)}.batch-bar span{margin-right:auto;font-size:12px}.batch-bar button{border:0;border-radius:10px;padding:9px 11px;color:#fff;background:#2563eb}.batch-bar .danger{background:#ef4444}</style>
