export type AiProviderPreset = {
  id: string;
  name: string;
  short: string;
  color: string;
  logo?: string;
  protocol: "openai";
  baseUrl: string;
  region: "domestic" | "global";
};

export const aiProviderPresets: AiProviderPreset[] = [
  {
    id: "openai",
    name: "OpenAI",
    short: "OA",
    logo: "openai.svg",
    color: "#111827",
    protocol: "openai",
    baseUrl: "https://api.openai.com/v1",
    region: "global",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude（兼容网关）",
    short: "AN",
    logo: "anthropic.svg",
    color: "#cc785c",
    protocol: "openai",
    baseUrl: "",
    region: "global",
  },
  {
    id: "google",
    name: "Google Gemini",
    short: "G",
    logo: "google.svg",
    color: "#4285f4",
    protocol: "openai",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    region: "global",
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    short: "AZ",
    logo: "azure.svg",
    color: "#0078d4",
    protocol: "openai",
    baseUrl: "",
    region: "global",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    short: "MI",
    logo: "mistral.svg",
    color: "#f97316",
    protocol: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    region: "global",
  },
  {
    id: "groq",
    name: "Groq",
    short: "GQ",
    logo: "groq.svg",
    color: "#f55036",
    protocol: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    region: "global",
  },
  {
    id: "xai",
    name: "xAI Grok",
    short: "xAI",
    logo: "xai.svg",
    color: "#111111",
    protocol: "openai",
    baseUrl: "https://api.x.ai/v1",
    region: "global",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    short: "OR",
    logo: "openrouter.svg",
    color: "#6366f1",
    protocol: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    region: "global",
  },
  {
    id: "cohere",
    name: "Cohere",
    short: "CO",
    logo: "cohere.svg",
    color: "#39594d",
    protocol: "openai",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    region: "global",
  },
  {
    id: "meta",
    name: "Meta Llama",
    short: "L",
    logo: "meta.svg",
    color: "#0668e1",
    protocol: "openai",
    baseUrl: "",
    region: "global",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    short: "DS",
    logo: "deepseek.svg",
    color: "#4d6bfe",
    protocol: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    region: "domestic",
  },
  {
    id: "qwen",
    name: "阿里云通义千问",
    short: "QW",
    logo: "qwen.svg",
    color: "#615ced",
    protocol: "openai",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    region: "domestic",
  },
  {
    id: "zhipu",
    name: "智谱 GLM",
    short: "GLM",
    logo: "zhipu.svg",
    color: "#2563eb",
    protocol: "openai",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    region: "domestic",
  },
  {
    id: "moonshot",
    name: "月之暗面 Kimi",
    short: "K",
    logo: "moonshot.svg",
    color: "#111827",
    protocol: "openai",
    baseUrl: "https://api.moonshot.cn/v1",
    region: "domestic",
  },
  {
    id: "baichuan",
    name: "百川智能",
    short: "BC",
    logo: "baichuan.svg",
    color: "#1677ff",
    protocol: "openai",
    baseUrl: "https://api.baichuan-ai.com/v1",
    region: "domestic",
  },
  {
    id: "yi",
    name: "零一万物 Yi",
    short: "Yi",
    logo: "yi.svg",
    color: "#10b981",
    protocol: "openai",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    region: "domestic",
  },
  {
    id: "doubao",
    name: "火山方舟 / 豆包",
    short: "DB",
    logo: "doubao.svg",
    color: "#2f54eb",
    protocol: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    region: "domestic",
  },
  {
    id: "siliconflow",
    name: "硅基流动",
    short: "SF",
    logo: "siliconflow.svg",
    color: "#16a34a",
    protocol: "openai",
    baseUrl: "https://api.siliconflow.cn/v1",
    region: "domestic",
  },
  {
    id: "minimax",
    name: "MiniMax",
    short: "MM",
    logo: "minimax.svg",
    color: "#f43f5e",
    protocol: "openai",
    baseUrl: "https://api.minimax.chat/v1",
    region: "domestic",
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    short: "ST",
    logo: "stepfun.svg",
    color: "#7c3aed",
    protocol: "openai",
    baseUrl: "https://api.stepfun.com/v1",
    region: "domestic",
  },
  {
    id: "custom",
    name: "其他 OpenAI 兼容平台",
    short: "AI",
    color: "#475569",
    protocol: "openai",
    baseUrl: "",
    region: "global",
  },
];

export const providerPreset = (id?: string) =>
  aiProviderPresets.find((item) => item.id === id) || aiProviderPresets.at(-1)!;
export const providerLogoBackground = (preset: AiProviderPreset) =>
  preset.logo ? "#fff" : preset.color;
export function modelProviderPreset(
  modelId?: string,
  connectionProviderId?: string,
) {
  const id = String(modelId || "").toLowerCase();
  const rules: [RegExp, string][] = [
    [
      /^(gpt-|o[1345](?:-|$)|chatgpt|codex|dall-e|text-embedding|whisper|tts-|sora)/,
      "openai",
    ],
    [/claude/, "anthropic"],
    [/gemini|gemma/, "google"],
    [/deepseek/, "deepseek"],
    [/qwen|qwq/, "qwen"],
    [/glm|chatglm|cogview/, "zhipu"],
    [/kimi|moonshot/, "moonshot"],
    [/baichuan/, "baichuan"],
    [/(^|\/)yi-|yi-lightning/, "yi"],
    [/doubao|skylark/, "doubao"],
    [/mistral|mixtral|codestral|ministral/, "mistral"],
    [/llama|codellama/, "meta"],
    [/grok/, "xai"],
    [/command-r|aya-/, "cohere"],
    [/minimax|abab/, "minimax"],
    [/step-/, "stepfun"],
  ];
  return providerPreset(
    rules.find(([pattern]) => pattern.test(id))?.[1] || connectionProviderId,
  );
}
